#!/usr/bin/env php
<?php
include __DIR__ . '/../../include/arhone/autoload.php';

set_time_limit(0);

if (!empty($argv)) {

    array_shift($argv);
    $argv = array_flip($argv);

    if (isset($argv['--develop']) || isset($argv['-d'])) {

        $_SERVER['DEVELOP'] = true; // Режим разрабочика
        unset($argv['--develop']);
        unset($argv['-d']);

    }

    if (isset($argv['--test']) || isset($argv['-t'])) {

        $_SERVER['TEST'] = true; // Режим тестирования
        unset($argv['--test']);
        unset($argv['-t']);

    }

    if (isset($argv['-td']) || isset($argv['-dt'])) {

        $_SERVER['DEVELOP'] = true; // Режим разрабочика
        $_SERVER['TEST'] = true; // Режим тестирования
        unset($argv['-td']);
        unset($argv['-dt']);

    }

    $Builder = new arhone\builder\Builder(include __DIR__ . '/../../config/arhone/builder.php');
    try {

        echo $Builder->make('Controller')->run('console:' . implode(' ', array_flip($argv)));

    } catch (Exception $Exception) {

        echo $Exception->getMessage();

    }


}
